### ISSUE TITLE
Auth using Google

### ISSUE THREAD

**Issue by bharatpaliwal-169** [bharatpaliwal-169/memofeed-frontend#1]
Unable to setup auth using react-google-login or @React-oauth/google npm packages. Tried all possible solutions but things are not working. another pain is it need us to clear cookies on each use which makes it even more difficult to build

Hence for v1 it is dropped.

<img width="519" alt="error" src="https://user-images.githubusercontent.com/56474196/171851193-1d2e2125-a379-491d-8324-e9f4e19b67ca.png">

**Comment by tandrew468** [comment]
`npm i react-google-login`  ? 
How is it not working is it not being imported correctly?  Do you have a branch where the error is replicated?

**Comment by bharatpaliwal-169** [comment]
> `npm i react-google-login` ? How is it not working is it not being imported correctly? Do you have a branch where the error is replicated?

Hey @tandrew468 i will create a seprate branch and push the code ,rn it is not, the packages are all installed properly it is because im using react 17+ and react-google-login is going to be depreciated.

using @react-oauth/google is making it difficult (see 2nd error) and there is no proper solution available

**Comment by tandrew468** [comment]
try Firebase instead

**Comment by bharatpaliwal-169** [comment]
> try Firebase instead

yes that could be the another approach ,which indeed is a really better and "developer friendly" approach. But it kills the entire purpose of building a project without using any other services (except npm packages). For now I will be dropping off Google Auth service as I am not willing to use Firebase services. Thanks Gentlemen for your advice:) Happy Coding!
